# Generated by Django 5.0.3 on 2024-03-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Surname', models.CharField(max_length=500)),
                ('Id_No', models.CharField(blank=True, max_length=200, null=True)),
                ('car_reg_No', models.CharField(blank=True, max_length=200, null=True)),
                ('car_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('make', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='files')),
            ],
        ),
    ]
