# Generated by Django 5.0.3 on 2024-03-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0002_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='image',
        ),
        migrations.AddField(
            model_name='driver',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='driver_pictures/'),
        ),
    ]
